### ISSUE TITLE
when i  run yarn build in cita-web-debugger  have a problem

### ISSUE THREAD

**Issue by liushooter** [cryptape/cita-sdk-js#116]
在 cita-sdk-js/packages/cita-web-debugger 执行 yarn build的时候 提示
`cita-sdk-js/packages/cita-web-debugger/node_modules/@cryptape/cita-sdk/lib/base/index.d.ts
(2,39): Cannot use namespace 'Web3' as a type.`

**Comment by zengbing15** [comment]
we are working on it.

**Comment by Keith-CY** [comment]
@liushooter The dep of `@cryptape/cita-sdk` has outdated, which should be `v0.23.0` now, I've updated it in the develop branch: https://github.com/cryptape/cita-sdk-js/commit/a3baddb1c8e4f184de36bb046fa979bc0c7d116e

**Comment by liushooter** [comment]
still build error， local environment problem or  ..... ?
can you build the chrome plugin crx ， only `cita-web-debugger` plugin？

**Comment by zengbing15** [comment]
> can you build the chrome plugin crx ， only `cita-web-debugger` plugin？

you can download it from here: https://github.com/cryptape/cita-sdk-js/releases

**Comment by Keith-CY** [comment]
> still build error， local environment problem or ..... ?
> 
> ```
> yarn  run build
> 
> yarn run v1.13.0
> warning ../../package.json: No license field
> $ react-scripts-ts build
> Creating an optimized production build...
> Starting type checking and linting service...
> Using 1 worker with 2048MB memory limit
> 
> ts-loader: Using typescript@3.4.5 and /Users/shooter/nervos/cita-sdk-js/packages/cita-web-debugger/tsconfig.prod.json
> Failed to compile.
> 
> Module not found: Error: Can't resolve './config' in 'nervos/cita-sdk-js/packages/cita-web-debugger/src'
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> can you build the chrome plugin crx ， only `cita-web-debugger` plugin？

As the log said, the `config` file missed. [`config.example`](https://github.com/cryptape/cita-sdk-js/blob/develop/packages/cita-web-debugger/src/config.ts.example) has been provided but the should be renamed to `config.ts`

Released package is [here](https://github.com/cryptape/cita-sdk-js/releases/tag/cita-web-debugger%400.2.6)

**Comment by liushooter** [comment]
>![image](https://user-images.githubusercontent.com/1235106/57520656-c4551900-7350-11e9-888c-27601edffbf3.png)

it work,  thank You !!!
