### ISSUE TITLE
why using nvm in CI?

### ISSUE THREAD

**Issue by rainchen** [cryptape/cita-sdk-js#271]
I found that there is a line of cmd: `$ nvm install 10.16` and it spent 3 seconds.
e.g.: https://travis-ci.org/cryptape/cita-sdk-js/jobs/607513630#L191

Why we need installing a nvm in CI env?

**Comment by Keith-CY** [comment]
I believe it's introduced by Travis for specifying the node version we set in the [travis.yml](https://github.com/cryptape/cita-sdk-js/blob/develop/.travis.yml#L4)

**Comment by rainchen** [comment]
I see, it's OK then.
